#Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iwayq-deploy
  labels:
    app: iwayq-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iwayq-app
  template:
    metadata:
      labels:
        app: iwayq-app
    spec:
      containers:
      - name: iwayq-container
        image: iwayqdockertest/iwayq:1.0
        ports:
        - containerPort: 8080
...

#Service Type nodePort
---
apiVersion: v1
kind: Service
metadata:
  name: iwayq-service
  labels:
    app: iwayq-app
spec:
  selector:
    app: iwayq-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
...